#login

POST http://127.0.0.1:8000/api/v1/login
Content-Type: application/json
Accept: application/json

{
  "usuario": "laura_mesera",
  "password": "mesera123"
}

###
#crear mesa

POST http://127.0.0.1:8000/api/v1/mesas
Content-Type: application/json
Accept: application/json

{
  "id_sucursal": 1,
  "numero_mesa": 6,
  "capacidad": 6,
  "estado": "Disponible"
}

###Listar todas las mesas
GET http://127.0.0.1:8000/api/v1/mesas
Accept: application/json

###Listar mesas de una sucursal
GET http://127.0.0.1:8000/api/v1/mesas?id_sucursal=1
Accept: application/json

###Cambiar estado de mesa
PUT http://127.0.0.1:8000/api/v1/mesas/3
Content-Type: application/json

{
  "estado": "Ocupada"
}

###  Eliminar mesa
DELETE http://127.0.0.1:8000/api/v1/mesas/3

### Listar menú
GET http://127.0.0.1:8000/api/v1/menu


### Listar platillos por categoría
GET http://127.0.0.1:8000/api/v1/menu?id_categoria=1


### crear platillo
POST http://127.0.0.1:8000/api/v1/menu
Content-Type: application/json

{
  "nombre": "Pizza Cuatro Quesos",
  "descripcion": "Mozzarella, parmesano, gorgonzola y provolone",
  "precio": 32000,
  "id_categoria": 1,
  "tiempo_preparacion": 18,
  "imagen": "uploads/pizzas/cuatro_quesos.jpg"
}

### ver platillo espesifico 
GET http://127.0.0.1:8000/api/v1/menu/1

### actualizar platillo
PUT http://127.0.0.1:8000/api/v1/menu/1
Content-Type: application/json

{
  "precio": 34000,
  "tiempo_preparacion": 20
}

### eliminar platillo
DELETE http://127.0.0.1:8000/api/v1/menu/2


### Crear pedido
POST http://127.0.0.1:8000/api/v1/pedidos
Content-Type: application/json

{
  "id_mesa": 1,
  "id_empleado": 1
}

### Actualizar pedido
PUT http://127.0.0.1:8000/api/v1/pedidos/5
Content-Type: application/json

{
  "estado": "En preparación",
  "total": 38000
}
### Listar pedidos
GET http://127.0.0.1:8000/api/v1/pedidos

### Ver pedido
GET http://127.0.0.1:8000/api/v1/pedidos/5

### Eliminar pedido
DELETE http://127.0.0.1:8000/api/v1/pedidos/5



### Listar detalles de un pedido
GET http://127.0.0.1:8000/api/v1/detalles?id_pedido=6

### Agregar detalle a un pedido
POST http://127.0.0.1:8000/api/v1/detalles
Content-Type: application/json

{
  "id_pedido": 6,
  "id_platillo": 3,
  "cantidad": 2
}

### Actualizar cantidad de un detalle
PUT http://127.0.0.1:8000/api/v1/detalles/9
Content-Type: application/json

{
  "cantidad": 3
}

### Eliminar detalle de un pedido
DELETE http://127.0.0.1:8000/api/v1/detalles/9


### Ver pedido completo con detalles
GET http://127.0.0.1:8000/api/v1/pedidos/6/detalle-completo



